exam8/ap_12/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from webapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexProductsListView.as_view(), name='index'),
    path('product/<int:id>', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:product_id>/update', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:product_id>/delete', views.ProductDeleteView.as_view(), name='product_delete'),
    path('product/add', views.ProductCreateView.as_view(), name='product_add'),
    path('product/<int:product_id>/reviews', views.ReviewCreateView.as_view(), name='review_add'),
    path('review/<int:id>', views.ReviewDetailView.as_view(), name='review_detail'),
    path('review/<int:review_id>/update', views.ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:review_id>/delete', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam8/ap_12/webapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from accounts.models import User
from django.contrib.auth import get_user_model


class Product(models.Model):
    CHOICES = [
        ("Components", "Components"),
        ("Laptops", "Laptops"),
        ("Smartphones", "Smartphones"),
        ("Periphery", "Periphery"),
    ]
    name = models.CharField(null=False, blank=False, max_length=40, verbose_name="Название")
    category = models.CharField(max_length=20, choices=CHOICES, verbose_name="Категория")
    description = models.TextField(max_length=400, null=True, blank=True, verbose_name="Описание")
    picture = models.ImageField(null=True, blank=True, upload_to='pictures', verbose_name="Картинка")

    def __str__(self):
        return self.name


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='reviews', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Автор')
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Товар')
    text = models.TextField(null=False, blank=False, max_length=800, verbose_name='Текст отзыва')
    grade = models.IntegerField(null=False, blank=False, validators=[MinValueValidator(1), MaxValueValidator(5)],
                                verbose_name='Оценка')

exam8/ap_12/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="text-center">
    {% if product.picture %}
    <img src="{{ product.picture.url }}" width="250" height="250" class="object-fit-cover" alt="picture">
    {% else %}
    <img src="{% static 'Placeholder-1.png' %}" width="250" height="250" class="object-fit-cover" alt="picture">
    {% endif %}
    <h2>Name: {{ product.name }}</h2>
    <p>Category: {{ product.category }}</p>
    <p>Description: {{ product.description }}</p>
    <p>Average grade: {% if average_grade %} {{ average_grade }} {% else %} 0 {% endif %}</p>
    {% if perms.webapp.change_product %}
    <a href="{% url 'product_update' product_id=product.id %}" class="btn btn-primary">
        Update
    </a>
    {% endif %}
    <br><br>
    {% if perms.webapp.delete_product %}
    <form action="{% url 'product_delete' product_id=product.id %}" method="post" onsubmit="return confirm('Delete?')">
        {% csrf_token %}
        <button class="btn btn-danger">Delete</button>
    </form>
    {% endif %}
    <hr>
    <h3 class="mb-4">Reviews</h3>
    {% url 'review_add' product_id=product.id as tasks_action_url %}
    {% include 'partial/form.html' with form=review_form request_method='POST' action_url=tasks_action_url %}
    <hr>
    {% for part in reviews %}
    <a href="{% url 'profile' id=part.author.id %}">{{ part.author.first_name }}</a><br><br>
    <p>Почта: {{ part.author.email }}</p>
    <p>Отзыв: {{ part.text }}</p>
    <p>Оценка: {{ part.grade }}</p>
    <a href="{% url 'review_detail' id=part.id %}">Подробнее</a><br><br>

    <hr>
    {% empty %}

        <h5>No tasks yet.</h5>
    {% endfor %}
</div>
{% endblock %}

exam8/ap_12/templates/product/product.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    {% include 'partial/form.html' with request_method='post' %}

{% endblock %}

exam8/ap_12/templates/product/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update Project</h1>

    <form action="{% url 'product_update' product_id=product.id %}" method="post">
        {% include 'partial/form.html' %}
    </form>
{% endblock %}