exam8/ap_12/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from webapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexProductsListView.as_view(), name='index'),
    path('product/<int:id>', views.ProductDetailView.as_view(), name='product_detail'),
    path('product/<int:product_id>/update', views.ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:product_id>/delete', views.ProductDeleteView.as_view(), name='product_delete'),
    path('product/add', views.ProductCreateView.as_view(), name='product_add'),
    path('product/<int:product_id>/reviews', views.ReviewCreateView.as_view(), name='review_add'),
    path('review/<int:id>', views.ReviewDetailView.as_view(), name='review_detail'),
    path('review/<int:review_id>/update', views.ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:review_id>/delete', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam8/ap_12/webapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from accounts.models import User
from django.contrib.auth import get_user_model


class Product(models.Model):
    CHOICES = [
        ("Components", "Components"),
        ("Laptops", "Laptops"),
        ("Smartphones", "Smartphones"),
        ("Periphery", "Periphery"),
    ]
    name = models.CharField(null=False, blank=False, max_length=40, verbose_name="Название")
    category = models.CharField(max_length=20, choices=CHOICES, verbose_name="Категория")
    description = models.TextField(max_length=400, null=True, blank=True, verbose_name="Описание")
    picture = models.ImageField(null=True, blank=True, upload_to='pictures', verbose_name="Картинка")

    def __str__(self):
        return self.name


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), related_name='reviews', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Автор')
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Товар')
    text = models.TextField(null=False, blank=False, max_length=800, verbose_name='Текст отзыва')
    grade = models.IntegerField(null=False, blank=False, validators=[MinValueValidator(1), MaxValueValidator(5)],
                                verbose_name='Оценка')

exam8/ap_12/templates/review/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">

    <h2>Продукт: {{ review.product }}</h2>
    <p>Пользователь: {{ review.author }}</p>
    <p>Почта: {{ review.author.email }}</p>
    <p>Отзыв: {{ review.text }}</p>
    <p>Оценка: {{ review.grade }}</p>
    {% if perms.webapp.change_review or request.user == review.author %}
    <a href="{% url 'review_update' review_id=review.id %}" class="btn btn-primary">
        Update
    </a>
    {% endif %}
    <br><br>
    {% if perms.webapp.delete_review or request.user == review.author %}
    <form action="{% url 'review_delete' review_id=review.id %}" method="post" onsubmit="return confirm('Delete?')">
        {% csrf_token %}
        <button class="btn btn-danger">Delete</button>
    </form>
    {% endif %}
</div>
{% endblock %}

exam8/ap_12/templates/review/review.html
{% extends 'base.html' %}

{% block content %}

{% include 'partial/form.html' with request_method='post' %}

{% endblock %}

exam8/ap_12/templates/review/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update</h1>

    <form action="{% url 'review_update' review_id=review.id %}" method="post">
        {% include 'partial/form.html' %}
    </form>
{% endblock %}